%token EOF
%token PACKAGE
%token IMPORT STATIC
%token SEMICOLON DOT STAR OPENING_BRACKET CLOSING_BRACKET OPENING_PARENTHESIS CLOSING_PARENTHESIS OPENING_CHEVRON CLOSING_CHEVRON WILDCARD
%token CLASS INTERFACE ENUM
%token PUBLIC PRIVATE PROTECTED
%token ABSTRACT 
%token FINAL
%token SYNCHRONIZED
%token STRICTFP NATIVE
%token<string> IDENTIFIER
%token EXTENDS IMPLEMENTS SUPER
%token THROWS
%token COMMA
%token IF ELSE WHILE FOR
%token <int> INTEGER
%token <bool> BOOLEAN
%token VOID

%%

